# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- group: Snyk 

steps:
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'sonarcloud'
    organization: 'srivasarjit'
    scannerMode: 'Other'
    extraProperties: |
      # Additional properties that will be passed to the scanner,
      # Put one key=value per line, example:
      # sonar.exclusions=**/*.bin
      sonar.projectKey=srivasarjit_DevOps-Project
      sonar.projectName=DevOps Project
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: true
    sqMavenPluginVersionChoice: 'latest'

- task: CopyFiles@2
  inputs:
    Contents: '**'
    TargetFolder: '$(build.artifactstagingdirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'

#- task: Bash@3
#  continueOnError: true
#  inputs:
#    targetType: 'inline'
#    script: |
#      SNYK_TOKEN= $(SNYK_TOKEN)
#      export SNYK_TOKEN
#      mvn snyk:test
#  displayName: Snyk test

- task: SnykSecurityScan@1
  continueOnError: true
  inputs:
    serviceConnectionEndpoint: 'snyk'
    testType: 'app'
    monitorWhen: 'always'
    failOnIssues: true
- task: PowerShell@2
  inputs:
    filePath: '$(System.DefaultWorkingDirectory)/create_task.ps1'
- task: Docker@2
  inputs:
    containerRegistry: 'arjitdocker'
    repository: 'arjitks77/devsecops'
    command: 'build'
    Dockerfile: '**/Dockerfile'

- task: Bash@3
  displayName: Trivy Scan
  inputs:
    targetType: 'inline'
    script: |
      sudo apt-get install wget apt-transport-https gnupg lsb-release
      wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
      echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
      sudo apt-get update
      sudo apt-get install trivy

- task: CmdLine@2
  displayName: "Run trivy scan"
  inputs:
      script: |
        trivy image --exit-code 0 --severity LOW,MEDIUM azure:$(tag)
        trivy image --exit-code 1 --severity HIGH,CRITICAL azure:$(tag)