# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
- group: Synk

steps:

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      export SNYK_TOKEN
      mvn snyk: test -fn
